name = "findroot"
uuid = "0f4a4368-6e30-4c16-82a0-f5edd312a70e"
authors = ["Kiar Fatah"]
version = "0.1.0"

[compat]
julia = "1.7.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
